version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fipl-app
        ports:
            - '1080:8000'
        volumes:
            - .:/var/www:delegated
        depends_on:
            - db
        command: >
            sh -c "
                echo 'Clearing views...' &&
                php artisan view:clear &&
                echo 'Starting Laravel server...' &&
                php artisan serve --host=0.0.0.0 --port=8000
            "
    db:
        image: 'mysql:8.0'
        container_name: fipl-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: fiplDB
            MYSQL_USER: fiplUser
            MYSQL_PASSWORD: secretFiplJobs
        ports:
            - '3317:3306'
        volumes:
            - 'dbdata:/var/lib/mysql'
volumes:
    dbdata: